/*
 * Actualiza Datos Generales API
 * <p>API de Actualiza Datos Generales.</p><br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2020-10/circulo_de_credito-apihub.png' height='40' width='220'/></p><br/>
 *
 * OpenAPI spec version: 1.2.3
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.ActualizaDatosGenerales.client.api;

import io.ActualizaDatosGenerales.client.model.CatalogoEstados;
import io.ActualizaDatosGenerales.client.model.Errores;
import io.ActualizaDatosGenerales.client.model.RequestADG;
import io.ActualizaDatosGenerales.client.model.RespuestaADG;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.junit.Assert;
import org.junit.Before;

import io.ActualizaDatosGenerales.client.ApiClient;
import io.ActualizaDatosGenerales.client.ApiException;

import io.ActualizaDatosGenerales.interceptor.SignerInterceptor;
import okhttp3.OkHttpClient;


import java.util.concurrent.TimeUnit;

/**
 * API tests for AdgPorCuentaApi
 */
public class AdgPorCuentaApiTest {

    private final AdgPorCuentaApi api = new AdgPorCuentaApi();

    private Logger logger = LoggerFactory.getLogger(AdgPorCuentaApiTest.class.getName());

    private final SignerInterceptor interceptor = new SignerInterceptor();
    private ApiClient apiClient = null;

   
    
    @Before()
    public void setUp() {
        this.apiClient = api.getApiClient();
        this.apiClient.setBasePath("https://services.circulodecredito.com.mx/v1/adg");
        OkHttpClient okHttpClient = new OkHttpClient().newBuilder()
                .readTimeout(30, TimeUnit.SECONDS)
                .addInterceptor(new SignerInterceptor())
                .build();
        apiClient.setHttpClient(okHttpClient);
    }

    /**
     * Actualiza Datos Generales por cuenta
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void porCuentaPostTest() throws Exception {
     
        String xApiKey = "x-api-key";
        String username = "username";
        String password = "password";
      
        
        RequestADG requestBody = new RequestADG();
        requestBody.setClaveEstado(CatalogoEstados.DGO);
        requestBody.setNumOtorgante("000000");
        requestBody.setCuenta("CUENTA");
        requestBody.setCp("00000");
        requestBody.setFolioOtorgante("00000");
        RespuestaADG response = api.porCuentaPost( xApiKey, username, password, requestBody);
        logger.info(response.toString());
        Assert.assertTrue(response != null);
        Assert.assertTrue(response.getFolioConsulta() != null);
    
    }
    
}
